"""Initial migration(added analytics)

Revision ID: 6ec2f606c38d
Revises: 
Create Date: 2022-11-14 15:30:36.360729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec2f606c38d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joined_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_action_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_action_date')
    op.drop_column('user', 'joined_date')
    # ### end Alembic commands ###
