"""empty message

Revision ID: ef87577456a8
Revises: c8e60247164d
Create Date: 2023-01-17 16:22:38.173708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef87577456a8'
down_revision = 'c8e60247164d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'password_hash')
    # ### end Alembic commands ###
